obj-$(CONFIG_TIGON3) += tg3.o
obj-$(CONFIG_ATH9K) += ath9k.o
ath9k-$(CONFIG_ATH9K_PCI) += pci.o
ath9k-$(CONFIG_ATH9K_DEBUGFS) += debug.o
obj-$(CONFIG_ATH9K_HW) += ath9k_hw.o
obj-$(CONFIG_ATH9K_COMMON) += ath9k_common.o
obj-$(CONFIG_CHELSIO_LIB) += libcxgb.o
